AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SAM Template for EBS volume conversion

Resources:

    EBSVolumeConverter:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: s3://sanjdhar-sam-templates/gp3_upgrade.zip
            Handler: gp3_migrate_lambda.lambda_handler
            Runtime: python3.7
            Timeout: 120
            MemorySize: 128
            Policies:
            # Give just CRUD permissions to one table
            - DynamoDBCrudPolicy:
                TableName: !Ref EBSVolumeTable
            Environment:
                Variables:
                    DDB_TABLE_NAME: !Ref EBSVolumeTable
                    SNS_ARN: 'arn:aws:sns:us-east-1:065399810791:gp3_upgrade'

    EBSVolumeTable:
        Type: 'AWS::Serverless::SimpleTable'
        Properties:
            PrimaryKey:
                Name: volume_id
                Type: String
